import { Scope } from "@/types"

export const scopes: Scope[] = [
  "Artificial Intelligence and Machine Learning",
  "Computer Vision and Image Processing",
  "Natural Language Processing",
  "Speech Processing",
  "High Performance Computing",
  "Distributed Systems",
  "Pervasive Computing",
  "Information Retrieval",
  "Computational Science and Engineering",
  "Data Mining",
  "Information Technology Application",
  "Database and Programming",
  "Multimedia Services and Applications",
  "IT Audit, Security, and Governance",
  "Learning Systems",
  "Simulation",
  "Cryptography",
  "Numerical Methods",
  "Expert Systems: Concepts and Theory",
  "Recommendation Systems",
  "Recognition Systems",
  "Game Theory and Application",
  "Knowledge Modeling",
  "Cloud & Edge Computing",
  "AI Hardware & HPC",
  "Data & ML Infrastructure (MLOps, Big Data)",
  "Cybersecurity & Privacy in AI",
  "Ethical & Responsible AI",
  "IT/AI Governance & Compliance",
  "Transparency & Explainability",
  "Digital Transformation & Public Sector Strategies",
]
